version: "1.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: postgres
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
  bdConn:
    build:
      context: ./dbConn
      dockerfile: Dockerfile
